# Label Encoder

In [1]:
import pandas as pd
df = pd.DataFrame({'Name' : ['Aman','Nikita','Ajay','OM','Priya','Arpit','Arima']})
df.head()

     Name
0    Aman
1  Nikita
2    Ajay
3      OM
4   Priya

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [3]:
le.fit_transform(df['Name'])

array([1, 4, 0, 5, 6, 3, 2])

In [4]:
df['en_name'] = le.fit_transform(df['Name'])

In [5]:
df

     Name  en_name
0    Aman        1
1  Nikita        4
2    Ajay        0
3      OM        5
4   Priya        6
5   Arpit        3
6   Arima        2

In [6]:
New_data = df
New_data.to_csv('Label_Encoder.csv',index = False)